### ISSUE TITLE
Can I Ask Someone , 

### ISSUE THREAD

**Issue by hamid12121** [Ekey/KOK3.LPQ.Tool#1]
Hi Ekey , I'm Here Because Of Genshin Impact Decrypte Metadata 

Can U Help Me What Did U Used To Get 

1_ decryption_blob.bin
2_
var codeRegistration = baseaddr + 0x95E17F0;
 var metadataRegistration = baseaddr + 0xA747FA0;
3_
  stringLiterals = ReadMetadataClassArray<Il2CppStringLiteral>(0xDE220, (int)header.genericContainersOffset - 0xDE220); 
result = ReadStringToNull(0xCF1124 + index);

, 
Of Course U Will Help Me 😢
Will U?

**Comment by Ekey** [comment]
[khang06](https://github.com/khang06) explained how to do it [here](https://github.com/khang06/Il2CppDumper-YuanShen/pull/1#issuecomment-907731688)
