### ISSUE TITLE
Asking about file formats

### ISSUE THREAD

**Issue by fungnoth** [Ekey/KOK3.LPQ.Tool#2]
Thank you for deciphering this game. It's working for both kok3 and kok2 without changing anything.

Images, audio and text documents are fine.
But other things like obj, act, sce... which seems to be 3d related, 
Did you identify the format of it?
I tried importing objs into blender but it's not showing anything.

Please shed us some light on this, thanks.

**Comment by Ekey** [comment]
Idk about mesh files. You can ask about it on the Xentax forums in the 3d section [here](https://forum.xentax.com/viewforum.php?f=16), maybe someone can help you.
